version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'proxy_manager'
    networks:
      - nirvashare

    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  nirvashare: {}

