
services:

  onlyoffice:
    image: 'onlyoffice/documentserver'
    container_name: 'onlyoffice'
    user: root
    networks:
      - nirvashare
    restart: always
    ports:
      # Public HTTP Port:
      - '8085:80'
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: "__NS_SECRET__"
      ALLOW_PRIVATE_IP_ADDRESS: "true"

    volumes:
      - /var/nirvashare:/var/nirvashare

networks:
  nirvashare: {}


